version: '3.8'
services:
  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: dasmod/gateewayservice
    ports:
      - "8080:8080"

  event-service:
    build:
      context: ./booking
      dockerfile: Dockerfile
    image: dasmod/bookingservice
    ports:
      - "8060:8060"

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    image: dasmod/orderservice
    ports:
      - "8070:8070"
