version: '3.8'
services:
  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: dasmod/gateewayservice
    ports:
      - "8888:8888"

  event-service:
    build:
      context: ./booking
      dockerfile: Dockerfile
    image: dasmod/bookingservice
    ports:
      - "8060:8060"

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    image: dasmod/orderservice
    ports:
      - "8070:8070"

  notification-service:
    build:
      context: ./notification
      dockerfile: Dockerfile
    image: dasmod/notificationservice
    ports:
      - "8030:8030"

  frontend-service:
    build:
      context: ./frontend-driver
      dockerfile: Dockerfile
    image: dasmod/frontendservice
    ports:
      - "9000:9000"