spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      default-filters:
        - TokenRelay=
      routes:
        - id: event-service
          uri: http://localhost:8060
          predicates:
            - Path=/callme/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: IWLSnakHG8aNTWNaWuSj0a11UY4lzxd9
            authorization-grant-type: authorization_code
            scope: openid
  #          keycloak-without-test-scope:
  #            provider: keycloak
  #            client-id: spring-without-test-scope
  #            client-secret: f6fc369d-49ce-4132-8282-5b5d413eba23
  #            authorization-grant-type: authorization_code
  #            redirect-uri: "{baseUrl}/login/oauth2/code/spring-without-test-scope"


server:
  port: 80 #443
  ssl:
    enabled: false
    server:
      ssl:
        client-auth=none:
    key-store: classpath:keystore.p12
    key-store-password: 12345mo
    key-store-type: PKCS12
    key-alias: myalias


logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE