server:
  port: 8888
spring:
  main:
    web-application-type: reactive
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations